spring.mail.host: localhost
spring.mail.port: 25
spring.mail.username: hari.seldon@the-foundation.gal
spring.mail.password: Th3MuleWh0
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: false

pebble.suffix: .html
